version: "3"
#project_name: dev  # Specify your project name here
services:
  wap44:
    volumes:
      - .:/var/www/html
      - ./docker/env.sh:/var/www/html/config/k8s/.env
      - ./docker/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    build: .
    image: latheefp/wapi:latest
    # env_file:
    #   - docker/env.sh
    ports:
      - "8090:80"
      - "8080:8080"
    networks:
      - infratool     

networks:
  infratool:
    external: true

