version: "3"
#project_name: dev  # Specify your project name here
services:
  wap44:
    volumes:
      - D:\web\wa4.4:/var/www/html
      - D:\web\wa4.4\docker\env.sh:/var/www/html/config/k8s/.env
      - D:\web\wa4.4\docker\000-default.conf:/etc/apache2/sites-enabled/000-default.conf
#    build: .
    image: latheefp/wapi:latest
  #  image: grandhelp
    # env_file:
    #  - ./docker/env.sh
    ports:
      - "8001:80"
    networks:
      dev-network:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthcheck"]
      interval: 60s
      timeout: 5s
      retries: 3      
networks:
  dev-network:
    driver: bridge
