apiVersion: v1
kind: Config
clusters:
- name: "egrand"
  cluster:
    server: "https://rancher.egrand.in/k8s/clusters/c-m-k5l2jqvq"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GN3TURFMQpOelV6T0RBZUZ3MHlNekV4TVRZeE56VTROVGhhRncwek16RXhNVE14TnpVNE5UaGFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56QXdNVFUzTlRNNE1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRUdaaS9KTkNSVVdSdAp3L3Vhc1ByZzZkczg3bzR3ZUp1anRPT09pM\
      EoyVGo1cENMY1poYmQ4NU1TN25ZR2loWWhmaG9iblVLeU44bFFvCnF5K0F4SFVtbktOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGS\
      Tdrb0Y2eVI1Z2ZhZ0NDUExRcE1oYnQxRWZWTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEOQpNV\
      HJLYk1jWEpwdzZwSU1mZTN4MUVSQWlJcDQ5QURhQmpKUTcrSHlpVkFJZ1RSSWlaY0hpaWlmOE8xQ\
      kd2dFlVCkJ2d2FabWNxUEd3dlQ3U0FQK3EyanpnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "egrand"
  user:
    token: "kubeconfig-user-rpnt96d5b8:t4qnxwljhcdzhll7pqnxwzsq26pgmgpkp6jx24rmtqqncfhcjp26qn"


contexts:
- name: "egrand"
  context:
    user: "egrand"
    cluster: "egrand"

current-context: "egrand"
