name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Login to Docker Hub
    #   run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    #   env:
    #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    - name: Build and push Docker image
      env:
        IMAGE_TAG: latest  # Change this to your desired tag
      run: |
       # docker build -t your-registry/your-image-name:$IMAGE_TAG .
        docker build -t registry.egrand.in/wapi:$IMAGE_TAG .
        docker push registry.egrand.in/wapi:$IMAGE_TAG

    - name: Update Kubernetes deployment
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "$KUBE_CONFIG_DATA" | base64 -d > kubeconfig.yaml
        kubectl config use-context your-cluster-context
        kubectl set image deployment/your-deployment-name your-container-name=your-registry/your-image-name:$IMAGE_TAG