name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-action@v1

    - name: Build and push Docker image
      env:
        IMAGE_TAG: latest  # Change this to your desired tag
      run: |
       # docker build -t your-registry/your-image-name:$IMAGE_TAG .
        docker build -t registry.egrand.in/wapi:$IMAGE_TAG .
        docker push registry.egrand.in/wapi:$IMAGE_TAG

    - name: Update Kubernetes deployment
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "$KUBE_CONFIG_DATA" | base64 -d > kubeconfig.yaml
        kubectl config use-context your-cluster-context
        kubectl set image deployment/your-deployment-name your-container-name=your-registry/your-image-name:$IMAGE_TAG